apiVersion: v1
kind: Pod
metadata:
  name: multi-port-pod
spec:
  containers:
    - name: my-app
      image: my-app-image
      ports:
        - containerPort: 80   # HTTP
        - containerPort: 443  # HTTPS
        - containerPort: 8080 # Custom app port